// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuz5q2YduATtLFipGhbiDuzGnukhAh41g',
    appId: '1:499758128330:android:6e21ff0fd0bbca42376833',
    messagingSenderId: '499758128330',
    projectId: 'pillreminder-bbbe9',
    storageBucket: 'pillreminder-bbbe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxU5a_lwMSpf03sDRA89kSp1Gb4E8ULyI',
    appId: '1:499758128330:ios:d191d3ee80112575376833',
    messagingSenderId: '499758128330',
    projectId: 'pillreminder-bbbe9',
    storageBucket: 'pillreminder-bbbe9.appspot.com',
    androidClientId: '499758128330-9akjhetsqa1tk3n1g4feaj48vs20hl7d.apps.googleusercontent.com',
    iosClientId: '499758128330-vef1ifu2j86liiskja56r2a62feqnv9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
